# Generated by Django 5.1.2 on 2024-10-19 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalspa',
            options={'verbose_name': 'Medical Spa'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='serviceproduct',
            options={'verbose_name': 'Service Product'},
        ),
        migrations.AlterModelOptions(
            name='serviceproductprovider',
            options={'verbose_name': 'Service Product Provider'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Service Type'},
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(help_text='Represented in minutes', verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
