# Generated by Django 5.1.2 on 2024-10-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_spa', '0002_alter_medicalspa_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceproduct',
            unique_together={('name', 'type', 'provider')},
        ),
    ]
